# Generated by Django 3.1.1 on 2020-09-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0007_auto_20200923_1243"),
        ("bot", "0003_auto_20200923_2107"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("telegram_user", "manga")},
        ),
    ]
