# Generated by Django 3.1.1 on 2020-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="type",
        ),
        migrations.AddField(
            model_name="manga",
            name="genres",
            field=models.ManyToManyField(to="mangas.Genre", verbose_name="Gênero"),
        ),
        migrations.AddField(
            model_name="manga",
            name="types",
            field=models.ManyToManyField(to="mangas.Type", verbose_name="Tipos"),
        ),
    ]
