# Generated by Django 3.1.1 on 2020-09-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0003_auto_20200921_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mangas.author",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="designer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mangas.designer",
                verbose_name="Artista",
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="img_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="publish_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ano"),
        ),
    ]
