# Generated by Django 3.1.1 on 2020-09-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0004_auto_20200922_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mangas.author",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="designer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mangas.designer",
                verbose_name="Artista",
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="img_url",
            field=models.URLField(max_length=255, null=True, verbose_name="Imagem"),
        ),
        migrations.AlterField(
            model_name="manga",
            name="publish_year",
            field=models.IntegerField(null=True, verbose_name="Ano"),
        ),
    ]
