# Generated by Django 3.1.1 on 2020-09-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0006_auto_20200922_0954"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ("created_at",),
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
            },
        ),
        migrations.AlterModelOptions(
            name="designer",
            options={
                "ordering": ("created_at",),
                "verbose_name": "artista",
                "verbose_name_plural": "artistas",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("created_at",),
                "verbose_name": "gênero",
                "verbose_name_plural": "gêneros",
            },
        ),
        migrations.AlterModelOptions(
            name="manga",
            options={
                "ordering": ("created_at",),
                "verbose_name": "mangá",
                "verbose_name_plural": "mangás",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={
                "ordering": ("created_at",),
                "verbose_name": "tipo",
                "verbose_name_plural": "tipos",
            },
        ),
    ]
